// Write a java program using try catch block to handle java.lang.ArrayindexOutofBoundsException


public class exp25 {  
    public static void main(String[] args) {  
        try 
        {  
        int[] arr1= {24,23,234};
        System.out.println(arr1[4]);
        }  
            //handling the exception  
        catch(ArithmeticException e)  
        {  
            System.out.println(e);  
        }  
        System.out.println("rest of the code");  
    }     
}  
}
